---
- name: Reload systemd
  systemd:
    daemon_reload: true

- name: Restart redis-server
  service:
    name: redis-server
    state: restarted
    enabled: true

- name: Restart redis-sentinel
  service:
    name: redis-sentinel
    state: restarted
    enabled: true