all:
  vars:
    ansible_user: milad
    ansible_port: 22
    ansible_python_interpreter: /usr/bin/python3
    domain: cluster.local

  children:
    redis:
      hosts:
        redis-server-1:
          ansible_host: 192.168.122.11
          private_ip: 192.168.100.11
          role: master
        redis-server-2:
          ansible_host: 192.168.122.12
          private_ip: 192.168.100.12
          role: slave
        redis-server-3:
          ansible_host: 192.168.122.13
          private_ip: 192.168.100.13
          role: slave

    haproxy:
      hosts:
        haproxy-1:
          ansible_host: 192.168.122.14
          private_ip: 192.168.100.14
          keepalived_state: MASTER
          keepalived_priority: 101
        haproxy-2:
          ansible_host: 192.168.122.15
          private_ip: 192.168.100.15
          keepalived_state: BACKUP
          keepalived_priority: 100
