- name: Install chrony
  apt:
    name: chrony
    state: present
    update_cache: true

- name: Deploy chrony config
  copy:
    src: chrony.conf
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: "0644"
  notify: restart chrony

- name: Ensure chrony is enabled and running
  service:
    name: chrony
    enabled: true
    state: started
